// components/ui/container.tsx
import * as React from "react"

import { cn } from "@/lib/utils"

interface ContainerProps extends React.ComponentProps<"div"> {
  as?: React.ElementType
}

function Container({ className, as: Comp = "div", ...props }: ContainerProps) {
  return (
    <Comp
      data-slot="container"
      className={cn("@container", className)}
      {...props}
    />
  )
}

function ContainerInner({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="container-inner"
      className={cn("mx-auto w-full max-w-5xl", className)}
      {...props}
    />
  )
}

export { Container, ContainerInner }

// components/Container.vue
<script setup lang="ts">
interface ContainerProps {
  innerClass?: string
  outerClass?: string
}
defineProps<ContainerProps>()

const outer = ref()
const inner = ref()
</script>

<template>
    <div ref="outer" :class="`sm:px-8 ${outerClass}`">
      <div class="mx-auto max-w-7xl lg:px-8">
        <!--inner container-->
        <div ref="inner" :class="`relative px-4 sm:px-8 lg:px-12 ${innerClass}`">
            <div class="mx-auto max-w-2xl lg:max-w-5xl">
                <slot />
            </div>
        </div>
      </div>
    </div>
</template>

<style scoped>

</style>
